spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${database_url}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect